"""add permissions to project access and user create permission

Revision ID: 9113a3509a15
Revises: 98b49423774d
Create Date: 2025-12-26 15:56:04.153032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9113a3509a15'
down_revision = '98b49423774d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_read', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('can_edit', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('can_delete', sa.Boolean(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'can_create_projects',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('false'),
            )
        )
    op.alter_column('users', 'can_create_projects', server_default=None)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_create_projects')

    with op.batch_alter_table('project_access', schema=None) as batch_op:
        batch_op.drop_column('can_delete')
        batch_op.drop_column('can_edit')
        batch_op.drop_column('can_read')

    # ### end Alembic commands ###
